### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by MichaelSpencer1995** [mstiles92/stackmat#24]
Using the CDN for in browser usage.
The stackmat object is there in the console and the page asks to use my microphone 
but no console logs when I start and stop my timer.
My stackmat timer works in cstimer so it cant be that

**Comment by MichaelSpencer1995** [comment]
I really want to use my stackmat in my timer app so you are my only hope!

**Comment by stilesdev** [comment]
Unfortunately I have heard from several people that this doesn't work with their timers and/or computers.

I have a simple test page here that should help determine whether the library is reading your audio input correctly: https://stilesdev.github.io/stackmat/.

If your timer doesn't work there, then you are probably having the same issue. It's practically impossible for me to troubleshoot when this comes up, as this works with my Gen 4 SpeedStacks timer on all of the devices I have tested.

If your timer works with that test page but not in your own project, please provide a link to a reproduction and I'll do what I can to help.

**Comment by MichaelSpencer1995** [comment]
Oh I believe it is because I am using a G5 Timer

**Comment by stilesdev** [comment]
Yeah, that would probably be the issue. I lost interest in speedcubing about 4 years ago myself, so I've been out of the loop and didn't even know there was a G5 out now.

That being said, I honestly don't see me buying that timer or spending any time on adding support for it to this project. My job keeps me busy these days, so when I do any development outside of that, I'm usually only working on things that I currently find interesting or learning something new.

You may want to check out the solution posted in this other issue. I haven't tested it myself, but maybe this could be of some help? https://github.com/stilesdev/stackmat/issues/12#issuecomment-1251963833

There's no mention of the G5 timer on their page, but it looks like they hooked up my library with this project and got it working for them: https://github.com/Kubiverse/StackmatSignalProcessor

**Comment by MichaelSpencer1995** [comment]
Is there anyway you can help me. I want to mess around with your code and and see if I can get any input
from my g5 timer. How difficult is it for me to take your code and makes changes and then push it to unpkg.com like a umd build exactly like you did?

**Comment by MichaelSpencer1995** [comment]
Is there an easy way I can bundle up the ts into minified code on my local machine so that I can mess around with it in my timer app, and see if I can get any outputs in my console?
